# Generated by Django 2.1 on 2018-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinexchanges',
            name='m_area',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coinexchanges',
            name='m_exchange',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coinexchanges',
            name='m_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinexchanges',
            name='m_website',
            field=models.TextField(max_length=20),
        ),
    ]
