# Generated by Django 2.1 on 2018-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0005_auto_20180829_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelupdatetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_coinexchanges', models.DateTimeField(auto_now=True)),
                ('m_coinbar', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
