# Generated by Django 2.1 on 2018-09-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0006_modelupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbar',
            name='m_bch',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='coinbar',
            name='m_btc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='coinbar',
            name='m_eth',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='coinexchanges',
            name='m_bchpriceid',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='coinexchanges',
            name='m_btcpriceid',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='coinexchanges',
            name='m_ethpriceid',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_close',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_high',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_low',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_open',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_vol',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coinexchanges',
            name='m_website',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='modelupdatetime',
            name='m_coinbar',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modelupdatetime',
            name='m_coinexchanges',
            field=models.DateTimeField(),
        ),
    ]
