# Generated by Django 2.1 on 2018-09-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0008_auto_20180904_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinbar',
            old_name='m_bch',
            new_name='m_24hchange',
        ),
        migrations.RenameField(
            model_name='coinbar',
            old_name='m_btc',
            new_name='m_24hprice',
        ),
        migrations.RenameField(
            model_name='coinbar',
            old_name='m_close',
            new_name='m_24hvol',
        ),
        migrations.RenameField(
            model_name='coinbar',
            old_name='m_eth',
            new_name='m_price',
        ),
        migrations.RemoveField(
            model_name='coinbar',
            name='m_coinexchanges',
        ),
        migrations.RemoveField(
            model_name='coinbar',
            name='m_date',
        ),
        migrations.RemoveField(
            model_name='coinbar',
            name='m_high',
        ),
        migrations.RemoveField(
            model_name='coinbar',
            name='m_low',
        ),
        migrations.RemoveField(
            model_name='coinbar',
            name='m_open',
        ),
        migrations.RemoveField(
            model_name='coinbar',
            name='m_vol',
        ),
        migrations.AddField(
            model_name='coinbar',
            name='m_24hchangepercent',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='coinbar',
            name='m_coin',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='coinbar',
            name='m_name',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='coinbar',
            name='m_updatetime',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_symbol',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='Coinexchanges',
        ),
    ]
