# Generated by Django 2.1 on 2018-09-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0009_auto_20180907_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbar',
            name='m_website',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinbar',
            name='m_symbol',
            field=models.CharField(default='none', max_length=20, unique=True),
        ),
    ]
